add global modal system
pieslappa/acebook-gelato-geniuses pull request #20
Opened 2023-03-11 08:43 UTC by joel-powell

2023-03-12 06:27 UTC, terryhycheng requested changes
- Keep <App /> as clean as possible
- Move all context-related codes into `/context` folder and a single context file

2023-03-12 06:27 UTC, terryhycheng commented on frontend/src/components/app/App.js
> +    <ModalContext.Provider value={{ modals, pushModal }}>
`ModalContext.Provider` should be placed at the top of the component tree.

2023-03-12 06:27 UTC, terryhycheng commented on frontend/src/components/app/App.js
> +  const [modals, setModals] = useState([]);
These are the logic for modal context. They should be inside the context file instead of `App.js`

2023-03-12 06:27 UTC, terryhycheng commented on frontend/src/components/modalContext/ModalContext.js
> +
Should create a `ModalContextProvider` component to wrap everything inside, including states, functions and even the ModalView component.

2023-03-12 06:27 UTC, terryhycheng commented on frontend/src/components/modalView/ModalView.js
> +const ModalView = () => {
I would suggest to rename this as `ModalList`

2023-03-13 10:37 UTC, pieslappa approved these changes

2023-03-13 10:41 UTC, AmberG31 approved these changes

2023-03-13 10:42 UTC, AmberG31 approved these changes

2023-03-13 10:43 UTC, terryhycheng approved these changes

2023-03-13 10:43 UTC, merged