Global modal refactor
pieslappa/acebook-gelato-geniuses pull request #21
Opened 2023-03-12 06:31 UTC by terryhycheng

Most of them are just all housekeeping stuff :)

- Renamed `ModalView` to `ModalList`
- Moved all the context-related codes back to `src/contexts/modalContext.js`
- Moved provider to the top level of the component tree
- Added `useMemo` hook to prevent unnecessary rerender
- Added component tests to `ModalList`

2023-03-12 08:47 UTC, joel-powell requested changes

2023-03-12 08:47 UTC, joel-powell commented on frontend/src/contexts/modalContext.js
> +    setModals([...modals, newModal]);
Should we use prevState here as asynchronous methods can push modals?

2023-03-12 08:47 UTC, joel-powell commented on frontend/src/contexts/modalContext.js
> +  const context = useMemo(() => ({ modals, pushModal }), [modals]);
glad you managed to implement useMemo, couldn't quite figure it out!

2023-03-12 08:47 UTC, joel-powell commented on frontend/src/contexts/modalContext.js
> +const ModalContextProvider = ({ children }) => {
confused as to why we're passing in a prop of children here if there are no props being passed in in the index.js, am I missing something? 😅

2023-03-12 08:47 UTC, joel-powell commented on frontend/src/components/app/App.js
> +      <ModalList modals={modals} />
I think that as nothing else in app.js is using the context, there's even more of a case for just using the context inside of ModalList.

Then there's no need to use ModalContext in this file at all

2023-03-12 08:47 UTC, joel-powell commented on frontend/src/components/modalList/ModalList.js
> +const ModalList = ({ modals }) => {
I think we should get modals from the context rather than a prop here, as per my comment in app.js

2023-03-12 14:03 UTC, terryhycheng commented on frontend/src/contexts/modalContext.js
> +    setModals([...modals, newModal]);
I searched on Google but no comparison between `destructuring` and `concat` so  asked ChatGPT about this:

> Both the second (spread operator)  and third (concat one) solutions are valid ways of updating the state array, and there is no significant difference in terms of performance or correctness.
> 
> However, some developers may prefer the second solution because it uses the spread operator, which can be more familiar to developers who are used to working with arrays in JavaScript. Other developers may prefer the third solution because it uses the concat() method, which can be more performant in certain situations.
> 
> Ultimately, the choice between the two solutions is a matter of personal preference and style, and either one can be used to achieve the desired result.

I have no preference for this so I can change it back to concat if you have any concern :)

2023-03-12 14:05 UTC, terryhycheng commented on frontend/src/contexts/modalContext.js
> +const ModalContextProvider = ({ children }) => {
Sorry, I forgot one last commit last night :) Now, `<ModalList />` has been moved to modalContext.js

2023-03-12 14:09 UTC, terryhycheng commented on frontend/src/components/modalList/ModalList.js
> +const ModalList = ({ modals }) => {
Yes, we can but I wanted to set up component tests for this file so I make `modals` as props so that I have control over what to display in the tests :)

2023-03-12 14:15 UTC, terryhycheng commented on frontend/src/components/app/App.js
> +      <ModalList modals={modals} />
I forgot one commit last night, which moves all the logic back to ModalContext. Please check the latest one if it makes more sense to you

2023-03-12 15:57 UTC, joel-powell commented on frontend/src/contexts/modalContext.js
> +    setModals([...modals, newModal]);
I was actually talking about having the function inside of setModals which with your spread operator would be like:

`setModals((prevState) => [...prevState, newModal]);`

I opted for concat in mine as I thought it might be a little clearer for others.

2023-03-12 16:01 UTC, joel-powell commented on frontend/src/components/modalList/ModalList.js
> +const ModalList = ({ modals }) => {
I don't think we should compromise program structure for the sake of tests, I'm sure there's a way to work around that in the tests

2023-03-12 16:06 UTC, joel-powell commented on frontend/src/contexts/modalContext.js
> +const ModalContextProvider = ({ children }) => {
I do think `<ModalList />` should be staying in App.js as it is a part of the visual hierarchy.

2023-03-12 22:31 UTC, terryhycheng commented on frontend/src/contexts/modalContext.js
> +    setModals([...modals, newModal]);
I also agree that `concat()` is a better solution in terms of readability

2023-03-13 09:10 UTC, joel-powell approved these changes

2023-03-13 09:12 UTC, merged